# Generated by Django 4.0.3 on 2022-04-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0002_remove_students_degree'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
