# Generated by Django 4.0.3 on 2022-04-19 08:55

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['first_name', 'last_name'], unique=True),
        ),
    ]
