# Generated by Django 4.0.3 on 2022-04-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsapp', '0009_teacher_student_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='slug',
        ),
    ]
